In [139]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [140]:
movies=pd.read_csv("imdb.csv")
orgdata=movies

In [141]:
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

# TASK 1- Inspect the Data frame

In [142]:
movies.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [143]:
movies.shape

(5043, 28)

In [144]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5023 non-null   object
 19  language                   5031 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(12), int64(3), object(13)
memory usage: 1.1+ MB

# TASK 2- Cleaning the data

# Subtask 2.1 Inspect the null values

In [145]:
movies.isnull().sum(axis=0).sort_values(ascending=False) #null values according to column

gross                        884
budget                       492
aspect_ratio                 329
content_rating               303
plot_keywords                153
title_year                   108
director_name                104
director_facebook_likes      104
num_critic_for_reviews        50
actor_3_name                  23
actor_3_facebook_likes        23
num_user_for_reviews          20
color                         19
duration                      15
facenumber_in_poster          13
actor_2_name                  13
actor_2_facebook_likes        13
language                      12
actor_1_name                   7
actor_1_facebook_likes         7
country                        5
movie_facebook_likes           0
genres                         0
movie_title                    0
num_voted_users                0
movie_imdb_link                0
imdb_score                     0
cast_total_facebook_likes      0
dtype: int64

In [146]:
movies.isnull().sum(axis=1).sort_values(ascending=False) # null values according to row

279     15
4       13
4945    11
2241    11
2342    10
        ..
2708     0
2707     0
2706     0
2705     0
0        0
Length: 5043, dtype: int64

In [147]:
movies.isnull().sum(axis=0).sort_values(ascending=False)/len(movies)*100 #column wise null percentage

gross                        17.529248
budget                        9.756098
aspect_ratio                  6.523895
content_rating                6.008328
plot_keywords                 3.033908
title_year                    2.141582
director_name                 2.062265
director_facebook_likes       2.062265
num_critic_for_reviews        0.991473
actor_3_name                  0.456078
actor_3_facebook_likes        0.456078
num_user_for_reviews          0.396589
color                         0.376760
duration                      0.297442
facenumber_in_poster          0.257783
actor_2_name                  0.257783
actor_2_facebook_likes        0.257783
language                      0.237954
actor_1_name                  0.138806
actor_1_facebook_likes        0.138806
country                       0.099147
movie_facebook_likes          0.000000
genres                        0.000000
movie_title                   0.000000
num_voted_users               0.000000
movie_imdb_link               0.000000
imdb_score                    0.000000
cast_total_facebook_likes     0.000000
dtype: float64

# Subtask 2.2 Drop unnecessary columns

In [148]:
movies=movies.drop(["color","director_facebook_likes","actor_1_facebook_likes","actor_2_facebook_likes","actor_3_facebook_likes",
            "actor_2_name","cast_total_facebook_likes","actor_3_name","duration","facenumber_in_poster","content_rating",
            "country","movie_imdb_link","aspect_ratio","plot_keywords"],axis=1)

In [149]:
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,,NaN,NaN,NaN,7.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6,English,NaN,2013.0,7.7,84
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359,English,NaN,NaN,7.5,32000
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3,English,1400.0,2013.0,6.3,16
5041,Daniel Hsia,14.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9,English,NaN,2012.0,6.3,660
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84,English,1100.0,2004.0,6.6,456

# Subtask  2.3 Drop unnecessary rows using columns with high null percentages

In [68]:
round(movies.isnull().sum().sort_values(ascending=False)/len(movies)*100,2)

gross                     17.53
budget                     9.76
title_year                 2.14
director_name              2.06
num_critic_for_reviews     0.99
num_user_for_reviews       0.40
language                   0.24
actor_1_name               0.14
movie_facebook_likes       0.00
imdb_score                 0.00
num_voted_users            0.00
movie_title                0.00
genres                     0.00
dtype: float64

In [69]:
movies=movies[movies["gross"].notnull()]
movies=movies[movies["budget"].notnull()]

In [70]:
round(movies.isnull().sum().sort_values(ascending=False)/len(movies)*100,2)

language                  0.08
actor_1_name              0.08
num_critic_for_reviews    0.03
movie_facebook_likes      0.00
imdb_score                0.00
title_year                0.00
budget                    0.00
num_user_for_reviews      0.00
num_voted_users           0.00
movie_title               0.00
genres                    0.00
gross                     0.00
director_name             0.00
dtype: float64

# Subtask 2.4 Drop unnecessary rows

In [71]:
(movies.isnull().sum(axis=1).sort_values(ascending=False)>5).sum()  #drop unnecessary rows which have more than 5 nans values

0

# Subtask 2.5 Fill NaN values

In [72]:
movies.groupby("language").language.count().sort_values(ascending=False)

language
English       3707
French          37
Spanish         26
Mandarin        15
German          13
Japanese        12
Hindi           10
Cantonese        8
Italian          7
Korean           5
Portuguese       5
Norwegian        4
Hebrew           3
Persian          3
Dutch            3
Danish           3
Thai             3
Dari             2
Indonesian       2
Aboriginal       2
Icelandic        1
Hungarian        1
Arabic           1
Aramaic          1
Bosnian          1
Telugu           1
Czech            1
Swedish          1
Russian          1
Romanian         1
Dzongkha         1
None             1
Filipino         1
Mongolian        1
Maya             1
Kazakh           1
Vietnamese       1
Zulu             1
Name: language, dtype: int64

In [153]:
 movies["language"]=movies["language"].fillna("english")  # fill the missing rows in language column by english
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,,english,NaN,NaN,7.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6,English,NaN,2013.0,7.7,84
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359,English,NaN,NaN,7.5,32000
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3,English,1400.0,2013.0,6.3,16
5041,Daniel Hsia,14.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9,English,NaN,2012.0,6.3,660
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84,English,1100.0,2004.0,6.6,456

# Subtask 2.6 Check the number of retained rows

In [154]:
len(movies)

5043

In [155]:
len(movies)/len(orgdata)*100     # we have left around 77% of rows

100.0

# TASK 3: Data Analysis

# Subtask 3.1 : Change the unit of columns

In [156]:
movies["gross"]=movies["gross"]/100000
movies["budget"]=movies["budget"]/100000  # chnaging the unit of budget and gross column

In [157]:
movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,7605.05847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,2370.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,3094.04152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238,English,3000.0,2007.0,7.1,0
2,Sam Mendes,602.0,2000.74175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994,English,2450.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,4481.30642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701,English,2500.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,,english,NaN,NaN,7.1,0

# Subtask 3.2: Find the movies with the highest profit

In [158]:
movies["profit"]=movies["gross"]-movies["budget"]
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,7605.05847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,2370.000,2009.0,7.9,33000,5235.05847
1,Gore Verbinski,302.0,3094.04152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238,English,3000.000,2007.0,7.1,0,94.04152
2,Sam Mendes,602.0,2000.74175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994,English,2450.000,2015.0,6.8,85000,-449.25825
3,Christopher Nolan,813.0,4481.30642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701,English,2500.000,2012.0,8.5,164000,1981.30642
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,,english,NaN,NaN,7.1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6,English,NaN,2013.0,7.7,84,NaN
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359,English,NaN,NaN,7.5,32000,NaN
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3,English,0.014,2013.0,6.3,16,NaN
5041,Daniel Hsia,14.0,0.10443,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9,English,NaN,2012.0,6.3,660,NaN
5042,Jon Gunn,43.0,0.85222,Documentary,John August,My Date with Drew,4285,84,English,0.011,2004.0,6.6,456,0.84122

In [159]:
movies.sort_values(by="profit",ascending=False)

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,7605.05847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,2370.0000,2009.0,7.9,33000,5235.05847
29,Colin Trevorrow,644.0,6521.77271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290,English,1500.0000,2015.0,7.0,150000,5021.77271
26,James Cameron,315.0,6586.72302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528,English,2000.0000,1997.0,7.7,26000,4586.72302
3024,George Lucas,282.0,4609.35665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470,English,110.0000,1977.0,8.7,33000,4499.35665
3080,Steven Spielberg,215.0,4349.49459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515,English,105.0000,1982.0,7.9,34000,4244.49459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5036,Anthony Vallone,NaN,NaN,Crime|Drama,Richard Jewell,The Mongol King,36,1,English,0.0325,2005.0,7.8,4,NaN
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6,English,NaN,2013.0,7.7,84,NaN
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359,English,NaN,NaN,7.5,32000,NaN
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3,English,0.0140,2013.0,6.3,16,NaN
5041,Daniel Hsia,14.0,0.10443,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9,English,NaN,2012.0,6.3,660,NaN

In [160]:
top_10=movies.sort_values(by="profit",ascending=False).head(10)  # finding top 10 movies by profit
top_10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,7605.05847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,2370.0,2009.0,7.9,33000,5235.05847
29,Colin Trevorrow,644.0,6521.77271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290,English,1500.0,2015.0,7.0,150000,5021.77271
26,James Cameron,315.0,6586.72302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528,English,2000.0,1997.0,7.7,26000,4586.72302
3024,George Lucas,282.0,4609.35665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470,English,110.0,1977.0,8.7,33000,4499.35665
3080,Steven Spielberg,215.0,4349.49459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515,English,105.0,1982.0,7.9,34000,4244.49459
794,Joss Whedon,703.0,6232.79547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722,English,2200.0,2012.0,8.1,123000,4032.79547
17,Joss Whedon,703.0,6232.79547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722,English,2200.0,2012.0,8.1,123000,4032.79547
509,Roger Allers,186.0,4227.83777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656,English,450.0,1994.0,8.5,17000,3777.83777
240,George Lucas,320.0,4745.44677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597,English,1150.0,1999.0,6.5,13000,3595.44677
66,Christopher Nolan,645.0,5333.16061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667,English,1850.0,2008.0,9.0,37000,3483.16061

# Subtask 3.3 Drop duplicate values

In [161]:
movies.drop_duplicates(keep="first",inplace=True)

In [162]:
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,7605.05847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,2370.000,2009.0,7.9,33000,5235.05847
1,Gore Verbinski,302.0,3094.04152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238,English,3000.000,2007.0,7.1,0,94.04152
2,Sam Mendes,602.0,2000.74175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994,English,2450.000,2015.0,6.8,85000,-449.25825
3,Christopher Nolan,813.0,4481.30642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701,English,2500.000,2012.0,8.5,164000,1981.30642
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,,english,NaN,NaN,7.1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6,English,NaN,2013.0,7.7,84,NaN
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359,English,NaN,NaN,7.5,32000,NaN
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3,English,0.014,2013.0,6.3,16,NaN
5041,Daniel Hsia,14.0,0.10443,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9,English,NaN,2012.0,6.3,660,NaN
5042,Jon Gunn,43.0,0.85222,Documentary,John August,My Date with Drew,4285,84,English,0.011,2004.0,6.6,456,0.84122

In [163]:
top_10=movies.sort_values(by="profit",ascending=False).head(10)  # top 10 movies by profit without any duplicate values
top_10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,7605.05847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,2370.0,2009.0,7.9,33000,5235.05847
29,Colin Trevorrow,644.0,6521.77271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290,English,1500.0,2015.0,7.0,150000,5021.77271
26,James Cameron,315.0,6586.72302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528,English,2000.0,1997.0,7.7,26000,4586.72302
3024,George Lucas,282.0,4609.35665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470,English,110.0,1977.0,8.7,33000,4499.35665
3080,Steven Spielberg,215.0,4349.49459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515,English,105.0,1982.0,7.9,34000,4244.49459
17,Joss Whedon,703.0,6232.79547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722,English,2200.0,2012.0,8.1,123000,4032.79547
509,Roger Allers,186.0,4227.83777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656,English,450.0,1994.0,8.5,17000,3777.83777
240,George Lucas,320.0,4745.44677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597,English,1150.0,1999.0,6.5,13000,3595.44677
66,Christopher Nolan,645.0,5333.16061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667,English,1850.0,2008.0,9.0,37000,3483.16061
439,Gary Ross,673.0,4079.99255,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games,701607,1959,English,780.0,2012.0,7.3,140000,3299.99255

# Subtask 3.4 Find IMDB Top 250

In [164]:
movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,7605.05847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,2370.0,2009.0,7.9,33000,5235.05847
1,Gore Verbinski,302.0,3094.04152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238,English,3000.0,2007.0,7.1,0,94.04152
2,Sam Mendes,602.0,2000.74175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994,English,2450.0,2015.0,6.8,85000,-449.25825
3,Christopher Nolan,813.0,4481.30642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701,English,2500.0,2012.0,8.5,164000,1981.30642
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,,english,NaN,NaN,7.1,0,NaN

In [165]:
imdb_top_250=movies[movies["num_voted_users"]>25000].sort_values(by="imdb_score",ascending=False).head(250)
imdb_top_250     # created new data frame imdb_top_250 movies with highest imdb rating and the num of voted users > 25000

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
1937,Frank Darabont,199.0,283.41469,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144,English,250.0,1994.0,9.3,108000,33.41469
3466,Francis Ford Coppola,208.0,1348.21952,Crime|Drama,Al Pacino,The Godfather,1155770,2238,English,60.0,1972.0,9.2,43000,1288.21952
66,Christopher Nolan,645.0,5333.16061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667,English,1850.0,2008.0,9.0,37000,3483.16061
3481,NaN,54.0,NaN,Crime|Drama|Thriller,Kirsten Dunst,Fargo,170055,173,English,NaN,NaN,9.0,61000,NaN
2837,Francis Ford Coppola,149.0,573.00000,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650,English,130.0,1974.0,9.0,14000,443.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,J.J. Abrams,518.0,2577.04099,Action|Adventure|Sci-Fi,Chris Hemsworth,Star Trek,504419,1559,English,1500.0,2009.0,8.0,19000,1077.04099
119,Brad Bird,318.0,2064.35493,Animation|Comedy|Family|Fantasy,Janeane Garofalo,Ratatouille,473887,626,English,1500.0,2007.0,8.0,10000,564.35493
4144,Walter Salles,71.0,55.95428,Drama,Fernanda Montenegro,Central Station,28951,257,Portuguese,29.0,1998.0,8.0,0,26.95428
4096,Terrence Malick,112.0,NaN,Drama|Romance,Sam Shepard,Days of Heaven,37594,181,English,30.0,1978.0,8.0,0,NaN
1868,Barry Levinson,100.0,1728.25435,Drama,Tom Cruise,Rain Man,383784,331,English,250.0,1988.0,8.0,12000,1478.25435

In [97]:
imdb_top_250["rank"]=imdb_top_250["imdb_score"].rank(method="first",ascending=False)
imdb_top_250                   # adding rank column in imdb_top_250 data frame according to imdb rating

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,rank
1937,Frank Darabont,199.0,2.834147e-10,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144,English,2.500000e-10,1994.0,9.3,108000,3.341469e-11,1.0
3466,Francis Ford Coppola,208.0,1.348220e-09,Crime|Drama,Al Pacino,The Godfather,1155770,2238,English,6.000000e-11,1972.0,9.2,43000,1.288220e-09,2.0
2837,Francis Ford Coppola,149.0,5.730000e-10,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650,English,1.300000e-10,1974.0,9.0,14000,4.430000e-10,3.0
66,Christopher Nolan,645.0,5.333161e-09,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667,English,1.850000e-09,2008.0,9.0,37000,3.483161e-09,4.0
4498,Sergio Leone,181.0,6.100000e-11,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780,Italian,1.200000e-11,1966.0,8.9,20000,4.900000e-11,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4931,John Carney,232.0,9.437933e-11,Drama|Music|Romance,Glen Hansard,Once,90827,329,English,1.800000e-12,2007.0,7.9,26000,9.257933e-11,246.0
2605,Ang Lee,287.0,1.280678e-09,Action|Drama|Romance,Chen Chang,"Crouching Tiger, Hidden Dragon",217740,1641,Mandarin,1.500000e-10,2000.0,7.9,0,1.130678e-09,247.0
3029,David O. Russell,410.0,9.357180e-10,Biography|Drama|Sport,Christian Bale,The Fighter,275869,389,English,2.500000e-10,2010.0,7.9,36000,6.857180e-10,248.0
2177,Tim Burton,111.0,5.636235e-10,Fantasy|Romance,Johnny Depp,Edward Scissorhands,357581,588,English,2.000000e-10,1990.0,7.9,16000,3.636235e-10,249.0
2487,George Cukor,82.0,7.200000e-10,Drama|Family|Musical|Romance,Jeremy Brett,My Fair Lady,66959,258,English,1.700000e-10,1964.0,7.9,0,5.500000e-10,250.0

In [98]:
imdb_top_250[imdb_top_250["language"]!="English"]  # top foreign language film

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,rank
4498,Sergio Leone,181.0,6.100000e-11,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780,Italian,1.200000e-11,1966.0,8.9,20000,4.900000e-11,5.0
4747,Akira Kurosawa,153.0,2.690610e-12,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596,Japanese,2.000000e-11,1954.0,8.7,11000,-1.730939e-11,17.0
4029,Fernando Meirelles,214.0,7.563397e-11,Crime|Drama,Alice Braga,City of God,533200,749,Portuguese,3.300000e-11,2002.0,8.7,28000,4.263397e-11,20.0
2373,Hayao Miyazaki,246.0,1.004989e-10,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902,Japanese,1.900000e-10,2001.0,8.6,28000,-8.950114e-11,23.0
4259,Florian Henckel von Donnersmarck,215.0,1.128466e-10,Drama|Thriller,Sebastian Koch,The Lives of Others,259379,407,German,2.000000e-11,2006.0,8.5,39000,9.284657e-11,35.0
4921,Majid Majidi,46.0,9.254020e-12,Drama|Family,Bahare Seddiqi,Children of Heaven,27882,130,Persian,1.800000e-12,1997.0,8.5,0,7.454020e-12,39.0
2323,Hayao Miyazaki,174.0,2.298191e-11,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570,Japanese,2.400000e-08,1997.0,8.4,11000,-2.397702e-08,47.0
2970,Wolfgang Petersen,96.0,1.143313e-10,Adventure|Drama|Thriller|War,Jürgen Prochnow,Das Boot,168203,426,German,1.400000e-10,1981.0,8.4,11000,-2.566866e-11,49.0
4105,Chan-wook Park,305.0,2.181290e-11,Drama|Mystery|Thriller,Min-sik Choi,Oldboy,356181,809,Korean,3.000000e-11,2003.0,8.4,43000,-8.187100e-12,57.0
4659,Asghar Farhadi,354.0,7.098492e-11,Drama|Mystery,Shahab Hosseini,A Separation,151812,264,Persian,5.000000e-12,2011.0,8.4,48000,6.598492e-11,58.0
1329,S.S. Rajamouli,44.0,6.498000e-11,Action|Adventure|Drama|Fantasy|War,Tamannaah Bhatia,Baahubali: The Beginning,62756,410,Telugu,1.802615e-10,2015.0,8.4,21000,-1.152815e-10,59.0
1298,Jean-Pierre Jeunet,242.0,3.320166e-10,Comedy|Romance,Mathieu Kassovitz,Amélie,534262,1314,French,7.700000e-10,2001.0,8.4,39000,-4.379834e-10,61.0
2734,Fritz Lang,260.0,2.643500e-13,Drama|Sci-Fi,Brigitte Helm,Metropolis,111841,413,German,6.000000e-11,1927.0,8.3,12000,-5.973565e-11,65.0
4033,Thomas Vinterberg,349.0,6.109680e-12,Drama,Thomas Bo Larsen,The Hunt,170155,249,Danish,3.800000e-11,2012.0,8.3,60000,-3.189032e-11,73.0
2829,Oliver Hirschbiegel,192.0,5.501940e-11,Biography|Drama|History|War,Thomas Kretschmann,Downfall,248354,564,German,1.350000e-10,2004.0,8.3,14000,-7.998060e-11,81.0
2551,Guillermo del Toro,406.0,3.762314e-10,Drama|Fantasy|War,Ivana Baquero,Pan's Labyrinth,467234,1083,Spanish,1.350000e-10,2006.0,8.2,27000,2.412314e-10,86.0
4000,Juan José Campanella,262.0,2.016742e-10,Drama|Mystery|Thriller,Ricardo Darín,The Secret in Their Eyes,131831,231,Spanish,2.000000e-11,2009.0,8.2,33000,1.816742e-10,97.0
3550,Denis Villeneuve,226.0,6.857096e-11,Drama|Mystery|War,Lubna Azabal,Incendies,80429,156,French,6.800000e-11,2010.0,8.2,37000,5.709600e-13,98.0
2047,Hayao Miyazaki,212.0,4.710455e-11,Adventure|Animation|Family|Fantasy,Christian Bale,Howl's Moving Castle,214091,330,Japanese,2.400000e-10,2004.0,8.2,13000,-1.928954e-10,100.0
2830,Alejandro Amenábar,157.0,2.086345e-11,Biography|Drama|Romance,Belén Rueda,The Sea Inside,64556,140,Spanish,1.000000e-10,2004.0,8.1,0,-7.913655e-11,110.0
2914,Je-kyu Kang,86.0,1.110186e-11,Action|Drama|War,Min-sik Choi,Tae Guk Gi: The Brotherhood of War,31943,224,Korean,1.280000e-10,2004.0,8.1,0,-1.168981e-10,119.0
4461,Thomas Vinterberg,98.0,1.647780e-11,Drama,Ulrich Thomsen,The Celebration,65951,258,Danish,1.300000e-11,1998.0,8.1,5000,3.477800e-12,127.0
3553,José Padilha,142.0,8.060000e-14,Action|Crime|Drama|Thriller,Wagner Moura,Elite Squad,81644,107,Portuguese,4.000000e-11,2007.0,8.1,11000,-3.991940e-11,143.0
3423,Katsuhiro Ôtomo,150.0,4.391620e-12,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430,Japanese,1.100000e-08,1988.0,8.1,0,-1.099561e-08,147.0
4267,Alejandro G. Iñárritu,157.0,5.383834e-11,Drama|Thriller,Adriana Barraza,Amores Perros,173551,361,Spanish,2.000000e-11,2000.0,8.1,11000,3.383834e-11,152.0
3456,Vincent Paronnaud,242.0,4.443403e-11,Animation|Biography|Drama|War,Catherine Deneuve,Persepolis,70194,158,French,7.300000e-11,2007.0,8.0,14000,-2.856597e-11,166.0
3344,Karan Johar,210.0,4.018695e-11,Adventure|Drama|Thriller,Shah Rukh Khan,My Name Is Khan,69759,235,Hindi,1.200000e-10,2010.0,8.0,27000,-7.981305e-11,175.0
4144,Walter Salles,71.0,5.595428e-11,Drama,Fernanda Montenegro,Central Station,28951,257,Portuguese,2.900000e-11,1998.0,8.0,0,2.695428e-11,177.0
4284,Ari Folman,231.0,2.283276e-11,Animation|Biography|Documentary|Drama|History|War,Ari Folman,Waltz with Bashir,46107,156,Hebrew,1.500000e-11,2008.0,8.0,0,7.832760e-12,181.0
4897,Sergio Leone,122.0,3.500000e-11,Action|Drama|Western,Clint Eastwood,A Fistful of Dollars,147566,235,Italian,2.000000e-12,1964.0,8.0,0,3.300000e-11,183.0
1171,Yimou Zhang,283.0,8.496100e-13,Action|Adventure|History,Jet Li,Hero,149414,841,Mandarin,3.100000e-10,2002.0,7.9,0,-3.091504e-10,212.0
2863,Clint Eastwood,251.0,1.375393e-10,Drama|History|War,Yuki Matsuzaki,Letters from Iwo Jima,132149,316,Japanese,1.900000e-10,2006.0,7.9,5000,-5.246069e-11,226.0
3264,Michael Haneke,447.0,2.253770e-12,Drama|Romance,Isabelle Huppert,Amour,70382,190,French,8.900000e-11,2012.0,7.9,33000,-8.674623e-11,229.0
3510,Yash Chopra,29.0,2.921738e-11,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119,Hindi,7.000000e-11,2004.0,7.9,2000,-4.078262e-11,233.0
3677,Christophe Barratier,112.0,3.629758e-11,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151,110,French,5.500000e-11,2004.0,7.9,0,-1.870242e-11,237.0
4415,Fabián Bielinsky,94.0,1.221261e-11,Crime|Drama|Thriller,Ricardo Darín,Nine Queens,38215,125,Spanish,1.500000e-11,2000.0,7.9,0,-2.787390e-12,243.0
4640,Cristian Mungiu,233.0,1.185783e-11,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763,172,Romanian,5.900000e-12,2007.0,7.9,14000,5.957830e-12,244.0
2605,Ang Lee,287.0,1.280678e-09,Action|Drama|Romance,Chen Chang,"Crouching Tiger, Hidden Dragon",217740,1641,Mandarin,1.500000e-10,2000.0,7.9,0,1.130678e-09,247.0

# Subtask 3.5 Find the best directors

In [104]:
top_10_director=movies.groupby("director_name").imdb_score.mean().sort_values(ascending=False).head(10)  
top_10_director        # extracting top 10 directors according to movie rating

director_name
Charles Chaplin      8.600000
Tony Kaye            8.600000
Ron Fricke           8.500000
Damien Chazelle      8.500000
Majid Majidi         8.500000
Alfred Hitchcock     8.500000
Sergio Leone         8.433333
Christopher Nolan    8.425000
Asghar Farhadi       8.400000
Richard Marquand     8.400000
Name: imdb_score, dtype: float64

# Subtask 3.6 Find popular genres

In [166]:
# genres columns in the dataframe with all the genres of the movies sepearted by a pipe(|).out of all the movies genres,the first two 
# two are most significant for any film.
# 1. Extract the first two genres from the genres column and store them in two new columns: genre_1 and genre_2.some of the movies
#    might have only one genre.In such situtaion,extract the single genre nto both the columns,for such movies the genre_2 will be 
#    the same as genre_1.
# 2. Group the dataframe using genre_1 as the primray column and genre_2 as the secondary column.
# 3. Find out the most popular combo of genres by finding the mean of the gross values using the gross column and store them in
#    a new dataframe name Popgenre.

In [112]:
tempgenre=movies.genres.str.split("|",expand=True).iloc[:,:2]
tempgenre.columns=["genre_1","genre_2"]

In [113]:
tempgenre

          genre_1    genre_2
0          Action  Adventure
1          Action  Adventure
2          Action  Adventure
3          Action   Thriller
5          Action  Adventure
...           ...        ...
5033        Drama     Sci-Fi
5034     Thriller       None
5035       Action      Crime
5037       Comedy      Drama
5042  Documentary       None

[3856 rows x 2 columns]

In [114]:
tempgenre.genre_2.fillna(tempgenre.genre_1,inplace=True)
tempgenre

          genre_1      genre_2
0          Action    Adventure
1          Action    Adventure
2          Action    Adventure
3          Action     Thriller
5          Action    Adventure
...           ...          ...
5033        Drama       Sci-Fi
5034     Thriller     Thriller
5035       Action        Crime
5037       Comedy        Drama
5042  Documentary  Documentary

[3856 rows x 2 columns]

In [115]:
movies=pd.concat([movies,tempgenre],axis=1)
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
0,James Cameron,723.0,7.605058e-09,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,2.370000e-09,2009.0,7.9,33000,5.235058e-09,Action,Adventure
1,Gore Verbinski,302.0,3.094042e-09,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238,English,3.000000e-09,2007.0,7.1,0,9.404152e-11,Action,Adventure
2,Sam Mendes,602.0,2.000742e-09,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994,English,2.450000e-09,2015.0,6.8,85000,-4.492583e-10,Action,Adventure
3,Christopher Nolan,813.0,4.481306e-09,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701,English,2.500000e-09,2012.0,8.5,164000,1.981306e-09,Action,Thriller
5,Andrew Stanton,462.0,7.305868e-10,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738,English,2.637000e-09,2012.0,6.6,24000,-1.906413e-09,Action,Adventure
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,4.247600e-12,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371,English,7.000000e-14,2004.0,7.0,19000,4.177600e-12,Drama,Sci-Fi
5034,Neill Dela Llana,35.0,7.007100e-13,Thriller,Ian Gamazon,Cavite,589,35,English,7.000000e-14,2005.0,6.3,74,6.307100e-13,Thriller,Thriller
5035,Robert Rodriguez,56.0,2.040920e-11,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130,Spanish,7.000000e-14,1992.0,6.9,0,2.033920e-11,Action,Crime
5037,Edward Burns,14.0,4.584000e-14,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14,English,9.000000e-14,2011.0,6.4,413,-4.416000e-14,Comedy,Drama
5042,Jon Gunn,43.0,8.522200e-13,Documentary,John August,My Date with Drew,4285,84,English,1.100000e-14,2004.0,6.6,456,8.412200e-13,Documentary,Documentary

In [118]:
movies.groupby(["genre_1","genre_2"]).gross.mean().sort_values(ascending=False).head(5)

genre_1    genre_2
Family     Sci-Fi       4.349495e-09
Adventure  Sci-Fi       2.286278e-09
           Family       1.189195e-09
           Animation    1.169985e-09
Action     Adventure    1.095955e-09
Name: gross, dtype: float64

# Subtask 3.7 : Find the critic favourite and audience-favorite actors

 1. create three new dataframes namely meryl_streep,leo_caprio and brad_pitt which contains the movies in which the actors:
    meryl_streep,leo_caprio and brad_pitt are the lead actors.Use only the actor_1 name column for extraction.Also,make sure 
    that you use the names "Meryl Streep",leo_caprio and brad_pitt for the said extraction.
 2. Append the rows of all the dataframes and store them in a new dataframe named combined.
 3. Group the combined dataframe using the actor_1_name column.
 4. Find the mean of the num_crirtic_for_reveiws and num_user_for_reveiws and identify the actors which have the highest mean.

In [122]:
meryl_streep=movies[movies["actor_1_name"]=="Meryl Streep"]
meryl_streep

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
410,Nancy Meyers,187.0,1.127035e-09,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860,214,English,8.500000e-10,2009.0,6.6,0,2.770347e-10,Comedy,Drama
1106,Curtis Hanson,42.0,4.681575e-10,Action|Adventure|Crime|Thriller,Meryl Streep,The River Wild,32544,69,English,4.500000e-10,1994.0,6.3,0,1.815748e-11,Action,Adventure
1204,Nora Ephron,252.0,9.412543e-10,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264,277,English,4.000000e-10,2009.0,7.0,13000,5.412543e-10,Biography,Drama
1408,David Frankel,208.0,1.247330e-09,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178,631,English,3.500000e-10,2006.0,6.8,0,8.973296e-10,Comedy,Drama
1483,Robert Redford,227.0,1.499807e-10,Drama|Thriller|War,Meryl Streep,Lions for Lambs,41170,298,English,3.500000e-10,2007.0,6.2,0,-2.000193e-10,Drama,Thriller
1575,Sydney Pollack,66.0,8.710000e-10,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339,200,English,3.100000e-10,1985.0,7.2,0,5.610000e-10,Biography,Drama
1618,David Frankel,234.0,6.353601e-10,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258,178,English,3.000000e-10,2012.0,6.3,0,3.353601e-10,Comedy,Drama
1674,Carl Franklin,64.0,2.320944e-10,Drama,Meryl Streep,One True Thing,9283,112,English,3.000000e-10,1998.0,7.0,592,-6.790560e-11,Drama,Drama
1925,Stephen Daldry,174.0,4.159783e-10,Drama|Romance,Meryl Streep,The Hours,102123,660,English,2.500000e-10,2002.0,7.6,0,1.659783e-10,Drama,Romance
2781,Phyllida Lloyd,331.0,2.995944e-10,Biography|Drama|History,Meryl Streep,The Iron Lady,82327,350,English,1.300000e-10,2011.0,6.4,18000,1.695944e-10,Biography,Drama
3135,Robert Altman,211.0,2.033861e-10,Comedy|Drama|Music,Meryl Streep,A Prairie Home Companion,19655,280,English,1.000000e-10,2006.0,6.8,683,1.033861e-10,Comedy,Drama

In [126]:
leo_caprio=movies[movies["actor_1_name"]=="Leonardo DiCaprio"]
leo_caprio

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
26,James Cameron,315.0,6.586723e-09,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528,English,2.000000e-09,1997.0,7.7,26000,4.586723e-09,Drama,Romance
50,Baz Luhrmann,490.0,1.448128e-09,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912,753,English,1.050000e-09,2013.0,7.3,115000,3.981280e-10,Drama,Romance
97,Christopher Nolan,642.0,2.925689e-09,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803,English,1.600000e-09,2010.0,8.8,175000,1.325689e-09,Action,Adventure
179,Alejandro G. Iñárritu,556.0,1.836359e-09,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188,English,1.350000e-09,2015.0,8.1,190000,4.863592e-10,Adventure,Drama
257,Martin Scorsese,267.0,1.026088e-09,Biography|Drama,Leonardo DiCaprio,The Aviator,264318,799,English,1.100000e-09,2004.0,7.5,0,-7.391173e-11,Biography,Drama
296,Quentin Tarantino,765.0,1.628046e-09,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193,English,1.000000e-09,2012.0,8.5,199000,6.280465e-10,Drama,Western
307,Edward Zwick,166.0,5.736626e-10,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292,657,English,1.000000e-09,2006.0,8.0,14000,-4.263374e-10,Adventure,Drama
308,Martin Scorsese,606.0,1.168667e-09,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588,1138,English,1.000000e-09,2013.0,8.2,138000,1.686673e-10,Biography,Comedy
326,Martin Scorsese,233.0,7.767964e-10,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033,1166,English,1.000000e-09,2002.0,7.5,0,-2.232036e-10,Crime,Drama
361,Martin Scorsese,352.0,1.323734e-09,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649,2054,English,9.000000e-10,2006.0,8.5,29000,4.237344e-10,Crime,Drama
452,Martin Scorsese,490.0,1.279684e-09,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092,964,English,8.000000e-10,2010.0,8.1,53000,4.796841e-10,Mystery,Thriller
641,Ridley Scott,238.0,3.938044e-10,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248,263,English,7.000000e-10,2008.0,7.1,0,-3.061956e-10,Action,Drama
911,Steven Spielberg,194.0,1.644352e-09,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667,English,5.200000e-10,2002.0,8.0,15000,1.124352e-09,Biography,Crime
990,Danny Boyle,118.0,3.977860e-10,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169,548,English,5.000000e-10,2000.0,6.6,0,-1.022140e-10,Adventure,Drama
1114,Sam Mendes,323.0,2.287781e-10,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591,414,English,3.500000e-10,2008.0,7.3,0,-1.212219e-10,Drama,Romance
1422,Randall Wallace,83.0,5.687637e-10,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219,244,English,3.500000e-10,1998.0,6.4,0,2.187637e-10,Action,Adventure
1453,Clint Eastwood,392.0,3.730495e-10,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728,279,English,3.500000e-10,2011.0,6.6,16000,2.304950e-11,Biography,Crime
1560,Sam Raimi,63.0,1.863654e-10,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197,216,English,3.200000e-10,1995.0,6.4,0,-1.336346e-10,Action,Thriller
2067,Jerry Zaks,45.0,1.278251e-10,Drama,Leonardo DiCaprio,Marvin's Room,20163,71,English,2.300000e-10,1996.0,6.7,1000,-1.021749e-10,Drama,Drama
2757,Baz Luhrmann,106.0,4.633873e-10,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750,506,English,1.450000e-10,1996.0,6.8,10000,3.183873e-10,Drama,Romance
3476,Baz Luhrmann,490.0,1.448128e-09,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933,753,English,1.050000e-09,2013.0,7.3,115000,3.981280e-10,Drama,Romance

In [129]:
brad_pitt=movies[movies["actor_1_name"]=="Brad Pitt"]
brad_pitt

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
101,David Fincher,362.0,1.274908e-09,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346,822,English,1.500000e-09,2008.0,7.8,23000,-2.250920e-10,Drama,Fantasy
147,Wolfgang Petersen,220.0,1.332283e-09,Adventure,Brad Pitt,Troy,381672,1694,English,1.750000e-09,2004.0,7.2,0,-4.177165e-10,Adventure,Adventure
254,Steven Soderbergh,198.0,1.255316e-09,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627,English,1.100000e-09,2004.0,6.4,0,1.553163e-10,Crime,Thriller
255,Doug Liman,233.0,1.863361e-09,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798,English,1.200000e-09,2005.0,6.5,0,6.633610e-10,Action,Comedy
382,Tony Scott,142.0,2.687100e-13,Action|Crime|Thriller,Brad Pitt,Spy Game,121259,361,English,9.200000e-10,2001.0,7.0,0,-9.197313e-10,Action,Crime
400,Steven Soderbergh,186.0,1.834058e-09,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845,English,8.500000e-10,2001.0,7.8,0,9.840577e-10,Crime,Thriller
470,David Ayer,406.0,8.570712e-10,Action|Drama|War,Brad Pitt,Fury,303185,701,English,6.800000e-10,2014.0,7.6,82000,1.770712e-10,Action,Drama
611,Jean-Jacques Annaud,76.0,3.790151e-10,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385,119,English,7.000000e-10,1997.0,7.0,0,-3.209849e-10,Adventure,Biography
683,David Fincher,315.0,3.702340e-10,Drama,Brad Pitt,Fight Club,1347461,2968,English,6.300000e-10,1999.0,8.8,48000,-2.597660e-10,Drama,Drama
792,Patrick Gilmore,98.0,2.628832e-10,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91,English,6.000000e-10,2003.0,6.7,880,-3.371168e-10,Adventure,Animation
940,Neil Jordan,120.0,1.052646e-09,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406,English,6.000000e-10,1994.0,7.6,11000,4.526461e-10,Drama,Fantasy
1490,Terrence Malick,584.0,1.330332e-10,Drama|Fantasy,Brad Pitt,The Tree of Life,136367,975,English,3.200000e-10,2011.0,6.7,39000,-1.869668e-10,Drama,Fantasy
1722,Andrew Dominik,273.0,3.904982e-11,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415,English,3.000000e-10,2007.0,7.5,0,-2.609502e-10,Biography,Crime
2204,Alejandro G. Iñárritu,285.0,3.430077e-10,Drama,Brad Pitt,Babel,243799,908,English,2.500000e-10,2006.0,7.5,0,9.300771e-11,Drama,Drama
2333,Angelina Jolie Pitt,131.0,5.310090e-12,Drama|Romance,Brad Pitt,By the Sea,7976,61,English,1.000000e-10,2015.0,5.3,0,-9.468991e-11,Drama,Romance
2682,Andrew Dominik,414.0,1.493857e-10,Crime|Thriller,Brad Pitt,Killing Them Softly,111625,369,English,1.500000e-10,2012.0,6.2,20000,-6.143000e-13,Crime,Thriller
2898,Tony Scott,122.0,1.228150e-10,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492,460,English,1.300000e-10,1993.0,8.0,15000,-7.185000e-12,Action,Crime

In [132]:
combined=meryl_streep.append([leo_caprio,brad_pitt])
combined

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
410,Nancy Meyers,187.0,1.127035e-09,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860,214,English,8.500000e-10,2009.0,6.6,0,2.770347e-10,Comedy,Drama
1106,Curtis Hanson,42.0,4.681575e-10,Action|Adventure|Crime|Thriller,Meryl Streep,The River Wild,32544,69,English,4.500000e-10,1994.0,6.3,0,1.815748e-11,Action,Adventure
1204,Nora Ephron,252.0,9.412543e-10,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264,277,English,4.000000e-10,2009.0,7.0,13000,5.412543e-10,Biography,Drama
1408,David Frankel,208.0,1.247330e-09,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178,631,English,3.500000e-10,2006.0,6.8,0,8.973296e-10,Comedy,Drama
1483,Robert Redford,227.0,1.499807e-10,Drama|Thriller|War,Meryl Streep,Lions for Lambs,41170,298,English,3.500000e-10,2007.0,6.2,0,-2.000193e-10,Drama,Thriller
1575,Sydney Pollack,66.0,8.710000e-10,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339,200,English,3.100000e-10,1985.0,7.2,0,5.610000e-10,Biography,Drama
1618,David Frankel,234.0,6.353601e-10,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258,178,English,3.000000e-10,2012.0,6.3,0,3.353601e-10,Comedy,Drama
1674,Carl Franklin,64.0,2.320944e-10,Drama,Meryl Streep,One True Thing,9283,112,English,3.000000e-10,1998.0,7.0,592,-6.790560e-11,Drama,Drama
1925,Stephen Daldry,174.0,4.159783e-10,Drama|Romance,Meryl Streep,The Hours,102123,660,English,2.500000e-10,2002.0,7.6,0,1.659783e-10,Drama,Romance
2781,Phyllida Lloyd,331.0,2.995944e-10,Biography|Drama|History,Meryl Streep,The Iron Lady,82327,350,English,1.300000e-10,2011.0,6.4,18000,1.695944e-10,Biography,Drama
3135,Robert Altman,211.0,2.033861e-10,Comedy|Drama|Music,Meryl Streep,A Prairie Home Companion,19655,280,English,1.000000e-10,2006.0,6.8,683,1.033861e-10,Comedy,Drama
26,James Cameron,315.0,6.586723e-09,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528,English,2.000000e-09,1997.0,7.7,26000,4.586723e-09,Drama,Romance
50,Baz Luhrmann,490.0,1.448128e-09,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912,753,English,1.050000e-09,2013.0,7.3,115000,3.981280e-10,Drama,Romance
97,Christopher Nolan,642.0,2.925689e-09,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803,English,1.600000e-09,2010.0,8.8,175000,1.325689e-09,Action,Adventure
179,Alejandro G. Iñárritu,556.0,1.836359e-09,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188,English,1.350000e-09,2015.0,8.1,190000,4.863592e-10,Adventure,Drama
257,Martin Scorsese,267.0,1.026088e-09,Biography|Drama,Leonardo DiCaprio,The Aviator,264318,799,English,1.100000e-09,2004.0,7.5,0,-7.391173e-11,Biography,Drama
296,Quentin Tarantino,765.0,1.628046e-09,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193,English,1.000000e-09,2012.0,8.5,199000,6.280465e-10,Drama,Western
307,Edward Zwick,166.0,5.736626e-10,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292,657,English,1.000000e-09,2006.0,8.0,14000,-4.263374e-10,Adventure,Drama
308,Martin Scorsese,606.0,1.168667e-09,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588,1138,English,1.000000e-09,2013.0,8.2,138000,1.686673e-10,Biography,Comedy
326,Martin Scorsese,233.0,7.767964e-10,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033,1166,English,1.000000e-09,2002.0,7.5,0,-2.232036e-10,Crime,Drama
361,Martin Scorsese,352.0,1.323734e-09,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649,2054,English,9.000000e-10,2006.0,8.5,29000,4.237344e-10,Crime,Drama
452,Martin Scorsese,490.0,1.279684e-09,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092,964,English,8.000000e-10,2010.0,8.1,53000,4.796841e-10,Mystery,Thriller
641,Ridley Scott,238.0,3.938044e-10,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248,263,English,7.000000e-10,2008.0,7.1,0,-3.061956e-10,Action,Drama
911,Steven Spielberg,194.0,1.644352e-09,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667,English,5.200000e-10,2002.0,8.0,15000,1.124352e-09,Biography,Crime
990,Danny Boyle,118.0,3.977860e-10,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169,548,English,5.000000e-10,2000.0,6.6,0,-1.022140e-10,Adventure,Drama
1114,Sam Mendes,323.0,2.287781e-10,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591,414,English,3.500000e-10,2008.0,7.3,0,-1.212219e-10,Drama,Romance
1422,Randall Wallace,83.0,5.687637e-10,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219,244,English,3.500000e-10,1998.0,6.4,0,2.187637e-10,Action,Adventure
1453,Clint Eastwood,392.0,3.730495e-10,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728,279,English,3.500000e-10,2011.0,6.6,16000,2.304950e-11,Biography,Crime
1560,Sam Raimi,63.0,1.863654e-10,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197,216,English,3.200000e-10,1995.0,6.4,0,-1.336346e-10,Action,Thriller
2067,Jerry Zaks,45.0,1.278251e-10,Drama,Leonardo DiCaprio,Marvin's Room,20163,71,English,2.300000e-10,1996.0,6.7,1000,-1.021749e-10,Drama,Drama
2757,Baz Luhrmann,106.0,4.633873e-10,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750,506,English,1.450000e-10,1996.0,6.8,10000,3.183873e-10,Drama,Romance
3476,Baz Luhrmann,490.0,1.448128e-09,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933,753,English,1.050000e-09,2013.0,7.3,115000,3.981280e-10,Drama,Romance
101,David Fincher,362.0,1.274908e-09,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346,822,English,1.500000e-09,2008.0,7.8,23000,-2.250920e-10,Drama,Fantasy
147,Wolfgang Petersen,220.0,1.332283e-09,Adventure,Brad Pitt,Troy,381672,1694,English,1.750000e-09,2004.0,7.2,0,-4.177165e-10,Adventure,Adventure
254,Steven Soderbergh,198.0,1.255316e-09,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627,English,1.100000e-09,2004.0,6.4,0,1.553163e-10,Crime,Thriller
255,Doug Liman,233.0,1.863361e-09,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798,English,1.200000e-09,2005.0,6.5,0,6.633610e-10,Action,Comedy
382,Tony Scott,142.0,2.687100e-13,Action|Crime|Thriller,Brad Pitt,Spy Game,121259,361,English,9.200000e-10,2001.0,7.0,0,-9.197313e-10,Action,Crime
400,Steven Soderbergh,186.0,1.834058e-09,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845,English,8.500000e-10,2001.0,7.8,0,9.840577e-10,Crime,Thriller
470,David Ayer,406.0,8.570712e-10,Action|Drama|War,Brad Pitt,Fury,303185,701,English,6.800000e-10,2014.0,7.6,82000,1.770712e-10,Action,Drama
611,Jean-Jacques Annaud,76.0,3.790151e-10,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385,119,English,7.000000e-10,1997.0,7.0,0,-3.209849e-10,Adventure,Biography
683,David Fincher,315.0,3.702340e-10,Drama,Brad Pitt,Fight Club,1347461,2968,English,6.300000e-10,1999.0,8.8,48000,-2.597660e-10,Drama,Drama
792,Patrick Gilmore,98.0,2.628832e-10,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91,English,6.000000e-10,2003.0,6.7,880,-3.371168e-10,Adventure,Animation
940,Neil Jordan,120.0,1.052646e-09,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406,English,6.000000e-10,1994.0,7.6,11000,4.526461e-10,Drama,Fantasy
1490,Terrence Malick,584.0,1.330332e-10,Drama|Fantasy,Brad Pitt,The Tree of Life,136367,975,English,3.200000e-10,2011.0,6.7,39000,-1.869668e-10,Drama,Fantasy
1722,Andrew Dominik,273.0,3.904982e-11,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415,English,3.000000e-10,2007.0,7.5,0,-2.609502e-10,Biography,Crime
2204,Alejandro G. Iñárritu,285.0,3.430077e-10,Drama,Brad Pitt,Babel,243799,908,English,2.500000e-10,2006.0,7.5,0,9.300771e-11,Drama,Drama
2333,Angelina Jolie Pitt,131.0,5.310090e-12,Drama|Romance,Brad Pitt,By the Sea,7976,61,English,1.000000e-10,2015.0,5.3,0,-9.468991e-11,Drama,Romance
2682,Andrew Dominik,414.0,1.493857e-10,Crime|Thriller,Brad Pitt,Killing Them Softly,111625,369,English,1.500000e-10,2012.0,6.2,20000,-6.143000e-13,Crime,Thriller
2898,Tony Scott,122.0,1.228150e-10,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492,460,English,1.300000e-10,1993.0,8.0,15000,-7.185000e-12,Action,Crime

In [133]:
combined.groupby("actor_1_name").num_critic_for_reviews.mean()

actor_1_name
Brad Pitt            245.000000
Leonardo DiCaprio    330.190476
Meryl Streep         181.454545
Name: num_critic_for_reviews, dtype: float64

In [135]:
combined["num_user_for_reviews"]=combined["num_user_for_reviews"].astype("int")
combined["num_user_for_reviews"]

410      214
1106      69
1204     277
1408     631
1483     298
1575     200
1618     178
1674     112
1925     660
2781     350
3135     280
26      2528
50       753
97      2803
179     1188
257      799
296     1193
307      657
308     1138
326     1166
361     2054
452      964
641      263
911      667
990      548
1114     414
1422     244
1453     279
1560     216
2067      71
2757     506
3476     753
101      822
147     1694
254      627
255      798
382      361
400      845
470      701
611      119
683     2968
792       91
940      406
1490     975
1722     415
2204     908
2333      61
2682     369
2898     460
Name: num_user_for_reviews, dtype: int32

In [136]:
combined.groupby("actor_1_name").num_user_for_reviews.mean()

actor_1_name
Brad Pitt            742.352941
Leonardo DiCaprio    914.476190
Meryl Streep         297.181818
Name: num_user_for_reviews, dtype: float64

In [138]:
combined.groupby("actor_1_name")[["num_critic_for_reviews","num_user_for_reviews"]].mean()

                   num_critic_for_reviews  num_user_for_reviews
actor_1_name
Brad Pitt                      245.000000            742.352941
Leonardo DiCaprio              330.190476            914.476190
Meryl Streep                   181.454545            297.181818